# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff-format          # formatter + import sort
      - id: ruff                 # linter
        args: ["--fix"]          # (optional) allow autofix
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
